name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies on Ubuntu
      if: runner.os != 'Windows'
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install pytest

    - name: Install dependencies on Windows
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        python -m venv venv
        .\venv\Scripts\Activate.ps1
        pip install pytest

    - name: Run tests on Ubuntu
      if: runner.os != 'Windows'
      run: |
        source venv/bin/activate
        pytest

    - name: Run tests on Windows
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        .\venv\Scripts\Activate.ps1
        pytest
